### ISSUE TITLE
Create Select room by id form

### ISSUE THREAD

**Issue by LucasLudueno** [mulesoft-labs/rooming#9]

**Comment by jmoguilevsky** [comment]
From the mockup:

![screen shot 2016-09-30 at 12 03 40 pm](https://cloud.githubusercontent.com/assets/4685055/18996253/f9d925b0-8705-11e6-8679-9bc7a0bdeea2.png)

**Comment by jmoguilevsky** [comment]
First version has diverged from the mockup to a filterable, clickeable listview 

![screen shot 2016-10-18 at 3 20 03 pm](https://cloud.githubusercontent.com/assets/4685055/19490815/ed1e8366-9546-11e6-9053-cef2e15c4196.png)
